version: '3.9'

services:
  app:
    image: hostnameserver
    build: ./app/
    # command:
    #   [
    #     "sh",
    #     "-c",
    #     "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"
    #   ]
    ports:
      - 5000:5000
      - 5678:5678
    depends_on:
      - db
    volumes:
      # - app_migrations:/usr/src/app/app_migrations
      - app_migrations:/usr/src/app/migrations
    env_file:
      - ./app/.env
    environment:
      - FLASK_ENV=docker
      - FLASK_APP=hostname_server/app.py
      - APP_DEBUG=true
  db:
    image: postgres:16.3
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  postgres-password:
    file: postgres-password.txt

volumes:
  db_data:
  app_migrations:
